blogger/config/routes.rb
Blogger::Application.routes.draw do

  root to: "articles#index"

  resources :articles do
    resources :comments, only: [ :create ]
  end

  resources :tags, only: [ :index, :show ]

  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login'  => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'

end

blogger/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list
  validates :title, :body, presence: true

  has_many :comments, dependent: :destroy

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings


  def tag_list
    tags.collect { |tag| tag.name }.join(", ")
  end

  def tag_list=(value)
    tag_names = tag_list_to_tag_names(value)
    found_tags = tag_names.map { |name| Tag.find_or_create_by_name name }
    self.tags = found_tags
  end

  def tag_list_to_tag_names(value)
    value.split(",").map {|name| name.strip.downcase }
  end

end

blogger/app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, 
    message: "should match confirmation", if: :password
end

blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :author, :body
  
  validates :author, :body, presence: true
end

blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def require_login
    if not logged_in?
      flash[:message] = "You must be logged in!"
      redirect_to login_path
    end
  end


end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :require_login, except: [ :index, :show ]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create params[:article]

    if @article.valid?
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes params[:article]

    # An alternative to updating the article
    # Article.update @article, params[:article]

    flash[:message] = "You're awesome, you updated the article"
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:message] = "You're awesome, You deleted article '#{@article.title}'"
    redirect_to articles_path
  end

end

blogger/app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  before_filter :require_login, except: [ :new, :create, :destroy ]

  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    if login(params[:username], params[:password])
      redirect_back_or_to articles_path, message: "Logged In Successfully"
    else
      flash[:message] = "Login Failed"
      render :new
    end
  end
  
  def destroy
    logout
    flash[:message] = 'Logged out!'
    redirect_to articles_path #, message: 'Logged out!'
  end

end

blogger/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_filter :require_login

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

end

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new params[:comment]
    @comment.article_id = params[:article_id]

    if @comment.save
      redirect_to article_path(@article)
    else
      render "articles/show"
    end
  end

end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show

    @tag = Tag.find_by_name(params[:id])

    if @tag.nil?
      flash[:message] = "The tag could not be found"
      redirect_to tags_path
    end

    # When the tag is not found redirect to the the tags index page
  end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/authors_helper.rb
module AuthorsHelper
end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/articles/_comment.html.erb
<div>
  <h4><%= comment_counter %> Comment by <%= comment.author %></h4>
  <p class="comment"><%= comment.body %></p>
</div>

blogger/app/views/articles/_comment_form.html.erb
<%= form_for [ @article, @comment ] do |f| %>
<p>
  <%= f.label :author %><br/>
  <%= f.text_field :author %><br/>
</p>
<p>
  <%= f.label :body %><br/>
  <%= f.text_area :body %><br/>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

blogger/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %><br/>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %><br/>
  </p>
  <p>
    <%= f.label :tag_list %><br/>
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

blogger/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form" %>

blogger/app/views/articles/index.html.erb
<h1>Articles</h1>
<ul id="articles">
<% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article_path(article) %>
  </li>
<% end %>
</ul>

<% if logged_in? %>
<%= link_to "Create Article", new_article_path, class: "new_article" %>
<% end %>

blogger/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form" %>

blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p class="body"><%= @article.body %></p>
<p>
  <h4>Tags:</h4>
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag.name) %>
  <% end %>
</p>

<hr/>

<%= render partial: "articles/comment", collection: @article.comments  %>

<%= render "articles/comment_form" %>

<% if logged_in? %>
<p class="article_actions">
  <%= link_to "Edit", edit_article_path(@article) %>
</p>
<p class="article_actions">
  <%= link_to "Delete", article_path(@article), 
        method: 'delete', confirm: "Are you sure you want to delete?" %>
</p>
<% end %>
<p class="article_actions">
  <%= link_to "Back to Index", articles_path %>
</p>

blogger/app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path do %>

<p>
  <%= label_tag :username %><br/>
  <%= text_field_tag :username %>
</p>
<p>
  <%= label_tag :password %><br/>
  <%= password_field_tag :password %>
</p>

<p>
  <%= submit_tag "Login" %>
</p>

<% end %>

blogger/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blogger/app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

blogger/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Password</th>
    <th>Password confirmation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.username %></td>
    <td><%= author.email %></td>
    <td><%= author.password %></td>
    <td><%= author.password_confirmation %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

blogger/app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

blogger/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @author.username %>
</p>

<p>
  <b>Email:</b>
  <%= @author.email %>
</p>

<p>
  <b>Password:</b>
  <%= @author.password %>
</p>

<p>
  <b>Password confirmation:</b>
  <%= @author.password_confirmation %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="flash"><%= flash[:message] %></p>
<%= yield %>
<hr>
<h6>
  <% if logged_in? %>
    <%= "Logged in as #{current_user.username}" %>
    <%= link_to "(logout)", logout_path %>
  <% else %>
    Logged out
    <%= link_to "(login)", login_path %>
  <% end %>
</h6>

</body>
</html>

blogger/app/views/tags/index.html.erb
<h1>Tags#index</h1>
<% @tags.each do |tag| %>
  <p><%= link_to tag.name, tag_path(tag.name) %></p>
<% end %>

blogger/app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<% @tag.articles.each do |article| %>
  <p><%= link_to article.title, article_path(article) %></p>
<% end %>